#pragma once
#ifndef __NEIGHBOUR_TILE__
#define __NEIGHBOUR_TILE__

enum NeighbourTile
{
	TOP_TILE,
	RIGHT_TILE,
	BOTTOM_TILE,
	LEFT_TILE,
	TOP_RIGHT_TILE,
	TOP_LEFT_TILE,
	BOTTOM_RIGHT_TILE,
	BOTTOM_LEFT_TILE,
	NUM_OF_NEIGHBOUR_TILES
};
#endif /* defined (__NEIGHBOUR_TILE__) */